### ISSUE TITLE
Image Quality Assessment

### ISSUE THREAD

**Issue by hangxiaotian** [YuanhaoGong/Naturalization#1]
老师，图像质量评价的那个自然性因子，三个通道计算出来，是三个通道都逼近1表示最好吗？

**Comment by YuanhaoGong** [comment]
是的。我们对三个通道分别进行了统计。发现三个通道的梯度分布几乎一致。所以在做naturalization的时候，可以三个通道分别做。

**Comment by hangxiaotian** [comment]
好的，非常谢谢老师，那如果这样的话，比如，该网址https://github.com/YuanhaoGong/Naturalization里面的Fig 5.14里面的第一行，去模糊的结果(第二幅图像)，算出三个通道的naturalization factor，即(0.51, 0.64, 0.80)，是不是针对三个通道与1之间的差，然后进行平方求和呢？不能根据某个通道与1的接近程度来度量吧？

**Comment by YuanhaoGong** [comment]
你那样算也行，但是更好的指标是给出三个值。因为是三个通道分别算的。你那样最终是给出一个值，不知道模糊是在哪个通道上。

**Comment by hangxiaotian** [comment]
非常谢谢老师，另外一个小问题，文章里写出，如果Nf的值小于1，则是被平滑了，如果大于1，则是被锐化了，我想用您的指标来进行评价图像增强后的结果。

**Comment by hangxiaotian** [comment]
另外，我做了几个实验进行了比较，对这个指标值有以下疑问：
I = imread('x.png'); % 读取的您代码里面的那个花的图像
figure,imshow(I)
Inoise = imnoise(I,'gaussian',0.02);
Iblur = imgaussfilt(I,2);
figure,imshow(Inoise);figure,imshow(Iblur);
然后分别计算这三个图像的Nf，其中读取的图像为您代码里面的那个花的图像。
I：2.7200    2.5246    2.0094
Inoise: 0.1568    0.1563    0.1612
Iblur: 4.7231    4.7895    4.7437
我做了十几个图像，然后发现Nf对高斯模糊比较敏感，但是，对于高斯噪声而言，Nf的值不敏感，这个指标是不是有改进的余地呢？老师

**Comment by YuanhaoGong** [comment]
可以用NF来评价噪声水平或者模糊程度。至于改进，我暂时没有好的想法。你可以尝试改进一下。

**Comment by hangxiaotian** [comment]
好的，非常谢谢老师的解释说明
